export const webDesignSkills = [
  'HTML',
  'CSS',
  'JavaScript',
  'Responsive Design',
  'UI/UX',
  'Wireframing',
  'Prototyping',
  'Figma',
  'Adobe XD',
  'Sketch',
  'Typography',
  'Color Theory',
  'User Research',
  'Accessibility',
  'Interaction Design',
  'Visual Design',
  'Grid Systems',
  'CSS Flexbox',
  'CSS Grid',
  'Animations',
  'Bootstrap',
  'Tailwind CSS',
  'Material UI',
  'Design Systems',
  'Information Architecture',
];

export const itCourses = [
  { title: "Full Stack Dev", instructor: "Angela Yu", rating: 4.9 },
  { title: "JS Course 2024", instructor: "Jonas Schmedtmann", rating: 4.8 },
  { title: "React Guide", instructor: "Maximilian Schwarzmüller", rating: 4.8 },
  { title: "Data Science Bootcamp", instructor: "Jose Portilla", rating: 4.7 },
  { title: "Python for All", instructor: "Charles Severance", rating: 4.8 },
  { title: "Intro to CS", instructor: "Eric Grimson", rating: 4.7 },
  { title: "Deep Learning", instructor: "Andrew Ng", rating: 4.9 },
  { title: "AWS Architect", instructor: "Andrew Brown", rating: 4.8 },
  { title: "Node.js Guide", instructor: "Stephen Grider", rating: 4.7 },
  { title: "Blockchain", instructor: "Harrison Chase", rating: 4.6 },
];

export const myskills = [
  'UI/UX',
  'Website Design',
  'Figma',
  'Animation',
  'User Persona',
  'XD',
];